export const homeScreenData = [
  {
    sno: '1',
    id: '1',
    title: 'The Downtown Pizzeria',
    foodname: 'Pizza, Fast Food',
    price: '350',
    image: require('../assets/pizza/img1.webp'),
    offer: '60% OFF today ',
    distance: '40 mins',
    location: 'Koramangala 5th Block, Bangalore',
    rating: '3.5',
  },
  {
    sno: '2',
    id: '1',
    title: "Domino's Pizza",
    foodname: 'Pizza, Fast Food, Italian',
    price: '150',
    image: require('../assets/pizza/img2.webp'),
    offer: '60% OFF today ',
    distance: '30 mins',
    location: 'Bangalore',
    rating: '4.2',
  },
  {
    sno: '3',
    id: '1',
    title: 'LeanCrust Pizza',
    foodname: 'Pizza, Italian',
    price: '150',
    image: require('../assets/pizza/img3.webp'),
    offer: '20% OFF today ',
    distance: '30 mins',
    location: 'Bangalore',
    rating: '3.9',
  },
  {
    sno: '4',
    id: '1',
    title: 'MOJO Pizza - 2X Toppings',
    foodname: 'Pizza, Fast Food',
    price: '250',
    image: require('../assets/pizza/img4.jpg'),
    offer: '60% OFF today ',
    distance: '21 mins',
    location: 'Bangalore',
    rating: '4.5',
  },
  {
    sno: '5',
    id: '1',
    title: "La Pino'z Pizza",
    foodname: 'Pizza, Fast Food, Beverages',
    price: '200',
    image: require('../assets/pizza/img5.webp'),
    offer: '60% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '4.0',
  },
  {
    sno: '6',
    id: '1',
    title: 'Pizza Hut',
    foodname: 'Pizza, Fast Food, Italian',
    price: '250',
    image: require('../assets/pizza/img6.webp'),
    offer: '70% OFF today ',
    distance: '27 mins',
    location: 'Bangalore',
    rating: '3.7',
  },
  {
    sno: '7',
    id: '1',
    title: 'Ovenstory Pizza',
    foodname: 'Pizza, Italian',
    price: '350',
    image: require('../assets/pizza/img7.webp'),
    offer: 'PRO 10% OFF',
    distance: '50 mins',
    location: 'Bangalore',
    rating: '3.8',
  },
  {
    sno: '8',
    id: '1',
    title: 'Fiero! Pizzeria',
    foodname: 'Pizza, Italian',
    price: '200',
    image: require('../assets/pizza/img8.webp'),
    offer: '30% OFF today ',
    distance: '39 mins',
    location: 'Bangalore',
    rating: '4.0',
  },
  {
    sno: '9',
    id: '1',
    title: 'Ludos Pizza',
    foodname: 'Pizza',
    price: '200',
    image: require('../assets/pizza/img9.webp'),
    offer: '60% OFF today ',
    distance: '46 mins',
    location: 'Bangalore',
    rating: '3.7',
  },
  {
    sno: '10',
    id: '1',
    title: 'Pizza Boss',
    foodname: 'Pizza, Fast Food',
    price: '150',
    image: require('../assets/pizza/img10.webp'),
    offer: '25% OFF today ',
    distance: '50 mins',
    location: 'Bangalore',
    rating: '3.5',
  },
  {
    sno: '11',
    id: '2',
    title: 'Anjappar',
    foodname: 'Chettinad, North Indian, Biryani',
    price: '250',
    image: require('../assets/biryani/img1.webp'),
    offer: '25% OFF today ',
    distance: '28 mins',
    location: 'Bangalore',
    rating: '3.9',
  },
  {
    sno: '12',
    id: '2',
    title: 'Ambur Biryani Point',
    foodname: 'Biryani, Kabab',
    price: '200',
    image: require('../assets/biryani/img2.jpg'),
    offer: '60% OFF today ',
    distance: '31 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '13',
    id: '2',
    title: 'Itminaan - Dum Biryani',
    foodname: 'Biryani, North Indian',
    price: '220',
    image: require('../assets/biryani/img3.webp'),
    offer: '60% OFF today ',
    distance: '24 mins',
    location: 'Bangalore',
    rating: '4.2',
  },
  {
    sno: '14',
    id: '2',
    title: "Mani's Dum Biryani",
    foodname: 'Biryani',
    price: '200',
    image: require('../assets/biryani/img4.jpg'),
    offer: '25% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '4.0',
  },
  {
    sno: '15',
    id: '2',
    title: 'Pot Biryani',
    foodname: 'Biryani, North Indian, Chinese',
    price: '200',
    image: require('../assets/biryani/img5.webp'),
    offer: '50% OFF today ',
    distance: '36 mins',
    location: 'Bangalore',
    rating: '3.8',
  },
  {
    sno: '16',
    id: '2',
    title: 'Paradise Biryani',
    foodname: 'Biryani, North Indian, Kebab',
    price: '300',
    image: require('../assets/biryani/img6.webp'),
    offer: '60% OFF today ',
    distance: '33 mins',
    location: 'Bangalore',
    rating: '3.9',
  },
  {
    sno: '17',
    id: '2',
    title: 'Biryani Wala online',
    foodname: 'Biryani, Rajasthani',
    price: '200',
    image: require('../assets/biryani/img7.webp'),
    offer: '50% OFF today ',
    distance: '38 mins',
    location: 'Bangalore',
    rating: '2.6',
  },
  {
    sno: '18',
    id: '2',
    title: 'Andhra Delight',
    foodname: 'PureVeg, Biryani',
    price: '250',
    image: require('../assets/biryani/img8.webp'),
    offer: '10% OFF today ',
    distance: '33 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '19',
    id: '2',
    title: 'Shanmukha',
    foodname: 'Biryani, Andhra, North Indian',
    price: '200',
    image: require('../assets/biryani/img9.jpg'),
    offer: 'PRO 20% OFF today ',
    distance: '43 mins',
    location: 'Bangalore',
    rating: '4.0',
  },
  {
    sno: '20',
    id: '2',
    title: 'Aligarh House',
    foodname: 'Biryani, North Indian, Mughlai',
    price: '250',
    image: require('../assets/biryani/img10.webp'),
    offer: '25% OFF today ',
    distance: '30 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '21',
    id: '3',
    title: 'Leon Grill',
    foodname: 'Burger, Fast Food, Wraps',
    price: '150',
    image: require('../assets/burger/img1.webp'),
    offer: '25% OFF today ',
    distance: '33 mins',
    location: 'Bangalore',
    rating: '4.2',
  },
  {
    sno: '22',
    id: '3',
    title: 'KFC',
    foodname: 'Burger, Fast Food, Beverages',
    price: '200',
    image: require('../assets/burger/img2.webp'),
    offer: '5% OFF today ',
    distance: '32 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '23',
    id: '3',
    title: "McDonald's",
    foodname: 'Burger, Fast Food, Beverages',
    price: '150',
    image: require('../assets/burger/img3.jpg'),
    offer: '40% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '4.0',
  },
  {
    sno: '24',
    id: '3',
    title: 'Bake and Juice',
    foodname: 'Burger, Arabian',
    price: '100',
    image: require('../assets/burger/img4.jpeg'),
    offer: '25% OFF today ',
    distance: '29 mins',
    location: 'Bangalore',
    rating: '3.6',
  },
  {
    sno: '25',
    id: '3',
    title: 'Biggies Burger',
    foodname: 'Burger, Fast Food, Beverages',
    price: '150',
    image: require('../assets/burger/img5.jpg'),
    offer: '60% OFF today ',
    distance: '33 mins',
    location: 'Bangalore',
    rating: '3.8',
  },
  {
    sno: '26',
    id: '3',
    title: 'Pop Burger',
    foodname: 'Burger, Fast Food',
    price: '150',
    image: require('../assets/burger/img6.webp'),
    offer: '45% OFF today ',
    distance: '38 mins',
    location: 'Bangalore',
    rating: '4.2',
  },
  {
    sno: '27',
    id: '3',
    title: 'Brothers Burger',
    foodname: 'Burger, Fast Food, American',
    price: '150',
    image: require('../assets/burger/img7.webp'),
    offer: '60% OFF today ',
    distance: '32 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '28',
    id: '3',
    title: 'Texas Burger',
    foodname: 'Burger, Fast Food, Beverages',
    price: '150',
    image: require('../assets/burger/img8.webp'),
    offer: '43% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '4.2',
  },
  {
    sno: '29',
    id: '3',
    title: 'Indiana Burger',
    foodname: 'Burger, Fast Food',
    price: 'PRO 20% OFF',
    image: require('../assets/burger/img9.webp'),
    offer: '25% OFF today ',
    distance: '35 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '30',
    id: '3',
    title: 'Frost & Feather',
    foodname: 'Burger, American',
    price: '100',
    image: require('../assets/burger/img10.webp'),
    offer: '13% OFF today ',
    distance: '55 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
  {
    sno: '31',
    id: '4',
    title: 'Sandwich Guru',
    foodname: 'Sandwich, Fast Food',
    price: '173',
    image: require('../assets/sandwich/img1.webp'),
    offer: '53% OFF today ',
    distance: '38 mins',
    location: 'Bangalore',
    rating: '2.8',
  },
  {
    sno: '32',
    id: '4',
    title: 'Subway',
    foodname: 'Wraps, Healthy Food, Sandwich',
    price: '128',
    image: require('../assets/sandwich/img2.webp'),
    offer: '41% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '2.5',
  },
  {
    sno: '33',
    id: '4',
    title: 'Sandwich Eats',
    foodname: 'Sandwich, Fast Food',
    price: '163',
    image: require('../assets/sandwich/img3.webp'),
    offer: '31% OFF today ',
    distance: '38 mins',
    location: 'Bangalore',
    rating: '4.9',
  },
  {
    sno: '34',
    id: '4',
    title: 'Sandwich Point',
    foodname: 'Sandwich, Fast Food',
    price: '126',
    image: require('../assets/sandwich/img4.jpg'),
    offer: '49% OFF today ',
    distance: '28 mins',
    location: 'Bangalore',
    rating: '4.5',
  },
  {
    sno: '35',
    id: '4',
    title: 'Sanwich Central',
    foodname: 'Sandwich, Fast Food',
    price: '165',
    image: require('../assets/sandwich/img5.webp'),
    offer: '35% OFF today ',
    distance: '27 mins',
    location: 'Bangalore',
    rating: '2.9',
  },
  {
    sno: '36',
    id: '4',
    title: 'SL Vadapav',
    foodname: 'Street Food, Fast Food, Sandwich',
    price: '50',
    image: require('../assets/sandwich/img6.webp'),
    offer: '34% OFF today ',
    distance: '23 mins',
    location: 'Bangalore',
    rating: '3.1',
  },
  {
    sno: '37',
    id: '4',
    title: 'Just Sandwich',
    foodname: 'Fast Food, Beverages, Sandwich',
    price: '107',
    image: require('../assets/sandwich/img7.webp'),
    offer: '53% OFF today ',
    distance: '27 mins',
    location: 'Bangalore',
    rating: '2.2',
  },
  {
    sno: '38',
    id: '4',
    title: 'Hari Super Sandwich',
    foodname: 'Sandwich, Fast Food',
    price: '175',
    image: require('../assets/sandwich/img8.webp'),
    offer: '28% OFF today ',
    distance: '30 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
  {
    sno: '39',
    id: '4',
    title: 'Sandwich Fit',
    foodname: 'Sandwich,  Fast Food',
    price: '166',
    image: require('../assets/sandwich/img9.webp'),
    offer: '20% OFF today ',
    distance: '28 mins',
    location: 'Bangalore',
    rating: '2.8',
  },
  {
    sno: '40',
    id: '4',
    title: 'Eat N Drink',
    foodname: 'Sandwich, Fast Food',
    price: '178',
    image: require('../assets/sandwich/img10.webp'),
    offer: '48% OFF today ',
    distance: '43 mins',
    location: 'Bangalore',
    rating: '3.5',
  },
  {
    sno: '41',
    id: '5',
    title: 'CakeZone',
    foodname: 'Bakery, Desserts',
    price: '200',
    image: require('../assets/cake/img1.jpeg'),
    offer: '50% OFF today ',
    distance: '29 mins',
    location: 'Bangalore',
    rating: '3.9',
  },
  {
    sno: '42',
    id: '5',
    title: 'WarmOven Cake',
    foodname: 'Bakery',
    price: '137',
    image: require('../assets/cake/img2.jpeg'),
    offer: '23% OFF today ',
    distance: '26 mins',
    location: 'Bangalore',
    rating: '2.9',
  },
  {
    sno: '43',
    id: '5',
    title: "Glen's Bakehouse",
    foodname: 'Bakery, Cafe, Fast Food',
    price: '110',
    image: require('../assets/cake/img3.jpeg'),
    offer: '44% OFF today ',
    distance: '32 mins',
    location: 'Bangalore',
    rating: '3.2',
  },
  {
    sno: '44',
    id: '5',
    title: 'Bakingo',
    foodname: 'Bakery, Desserts',
    price: '124',
    image: require('../assets/cake/img4.jpeg'),
    offer: '44% OFF today ',
    distance: '17 mins',
    location: 'Bangalore',
    rating: '3.1',
  },
  {
    sno: '45',
    id: '5',
    title: 'Cold Stone Creamery',
    foodname: 'Bakery, Desserts',
    price: '135',
    image: require('../assets/cake/img5.jpeg'),
    offer: '19% OFF today ',
    distance: '23 mins',
    location: 'Bangalore',
    rating: '3.2',
  },
  {
    sno: '46',
    id: '5',
    title: 'Cupcake Bliss Cakes',
    foodname: 'Bakery',
    price: '111',
    image: require('../assets/cake/img6.jpeg'),
    offer: '27% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '3.4',
  },
  {
    sno: '47',
    id: '5',
    title: 'Cake Box',
    foodname: 'Bakery, Desserts',
    price: '146',
    image: require('../assets/cake/img7.jpeg'),
    offer: '27% OFF today ',
    distance: '15 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
  {
    sno: '48',
    id: '5',
    title: 'Aubree',
    foodname: 'Bakery, Desserts',
    price: '132',
    image: require('../assets/cake/img8.jpeg'),
    offer: '23% OFF today ',
    distance: '23 mins',
    location: 'Bangalore',
    rating: '3.2',
  },
  {
    sno: '49',
    id: '5',
    title: 'The Cake Mart',
    foodname: 'Bakery',
    price: '127',
    image: require('../assets/cake/img9.jpeg'),
    offer: '25% OFF today ',
    distance: '24 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
  {
    sno: '50',
    id: '5',
    title: 'LayerBite',
    foodname: 'Bakery, Desserts, Beverages',
    price: '122',
    image: require('../assets/cake/img10.jpeg'),
    offer: '30% OFF today ',
    distance: '36 mins',
    location: 'Bangalore',
    rating: '2.8',
  },
  {
    sno: '51',
    id: '6',
    title: 'Bathinda Tandoor',
    foodname: 'Kebab, North Indian, Mughlai',
    price: '146',
    image: require('../assets/kebab/img1.jpeg'),
    offer: '15% OFF today ',
    distance: '18 mins',
    location: 'Bangalore',
    rating: '4.5',
  },
  {
    sno: '52',
    id: '6',
    title: 'Sharief Bhai',
    foodname: 'Kebab, Mughlai, Street Food',
    price: '144',
    image: require('../assets/kebab/img2.jpeg'),
    offer: '21% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '4.4',
  },
  {
    sno: '53',
    id: '6',
    title: 'Kebapci',
    foodname: 'Kebab, BBQ, Turkish, Middle Eastern',
    price: '130',
    image: require('../assets/kebab/img3.jpeg'),
    offer: '49% OFF today ',
    distance: '33 mins',
    location: 'Bangalore',
    rating: '3.9',
  },
  {
    sno: '54',
    id: '6',
    title: 'Punjabi Nawabi',
    foodname: 'Kebab, North Indian, Chinese',
    price: '120',
    image: require('../assets/kebab/img4.jpeg'),
    offer: '49% OFF today ',
    distance: '25 mins',
    location: 'Bangalore',
    rating: '3.2',
  },
  {
    sno: '55',
    id: '6',
    title: "Mani's Dum Biryani",
    foodname: 'Kebab',
    price: '120',
    image: require('../assets/kebab/img5.jpeg'),
    offer: '32% OFF today ',
    distance: '21 mins',
    location: 'Bangalore',
    rating: '2.6',
  },
  {
    sno: '56',
    id: '6',
    title: 'Rahhams',
    foodname: 'Kebab, North Indian, Kebab',
    price: '133',
    image: require('../assets/kebab/img6.jpeg'),
    offer: '37% OFF today ',
    distance: '29 mins',
    location: 'Bangalore',
    rating: '4.5',
  },
  {
    sno: '57',
    id: '6',
    title: 'Kebab-E-Sultanat',
    foodname: 'North Indian, Mughlai, Kebab',
    price: '137',
    image: require('../assets/kebab/img7.jpeg'),
    offer: '13% OFF today ',
    distance: '39 mins',
    location: 'Bangalore',
    rating: '4.4',
  },
  {
    sno: '58',
    id: '6',
    title: 'Sardarji Londonwaley',
    foodname: 'North Indian, Kebab',
    price: '107',
    image: require('../assets/kebab/img8.jpeg'),
    offer: '30% OFF today ',
    distance: '29 mins',
    location: 'Bangalore',
    rating: '2.1',
  },
  {
    sno: '59',
    id: '6',
    title: 'Bathinda Dine',
    foodname: 'North Indian, Kebab',
    price: '112',
    image: require('../assets/kebab/img9.jpeg'),
    offer: '48% OFF today ',
    distance: '31 mins',
    location: 'Bangalore',
    rating: '3.5',
  },
  {
    sno: '60',
    id: '6',
    title: 'AI Daaz',
    foodname: 'BBQ, North Indian, Kebab',
    price: '113',
    image: require('../assets/kebab/img10.jpeg'),
    offer: '14% OFF today ',
    distance: '20 mins',
    location: 'Bangalore',
    rating: '2.6',
  },
  {
    sno: '61',
    id: '7',
    title: 'Bathinda Tandoor',
    foodname: 'North Indian, Mughlai, Chicken',
    price: '133',
    image: require('../assets/chicken/img1.webp'),
    offer: '29% OFF today ',
    distance: '15 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '62',
    id: '7',
    title: 'Punjabi Nawabi',
    foodname: 'North Indian, Chinese, Biryani',
    price: '113',
    image: require('../assets/chicken/img2.webp'),
    offer: '13% OFF today ',
    distance: '39 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
  {
    sno: '63',
    id: '7',
    title: "McDonald's",
    foodname: 'Burger, Fast Food, Beverages, Chicken',
    price: '142',
    image: require('../assets/chicken/img3.jpg'),
    offer: '32% OFF today ',
    distance: '31 mins',
    location: 'Bangalore',
    rating: '2.2',
  },
  {
    sno: '64',
    id: '7',
    title: 'Kundana',
    foodname: 'Andhra, Mughlai, North Indian, Chicken',
    price: '113',
    image: require('../assets/chicken/img4.webp'),
    offer: '43% OFF today ',
    distance: '31 mins',
    location: 'Bangalore',
    rating: '2.1',
  },
  {
    sno: '65',
    id: '7',
    title: 'Sardarji Londonwaley',
    foodname: 'North Indian, Chinese, Biryani, Chicken',
    price: '133',
    image: require('../assets/chicken/img5.webp'),
    offer: '41% OFF today ',
    distance: '17 mins',
    location: 'Bangalore',
    rating: '4.6',
  },
  {
    sno: '66',
    id: '7',
    title: 'Bathinda Dine',
    foodname: 'North Indian, Chicken',
    price: '138',
    image: require('../assets/chicken/img6.jpg'),
    offer: '16% OFF today ',
    distance: '21 mins',
    location: 'Bangalore',
    rating: '2.5',
  },
  {
    sno: '67',
    id: '7',
    title: 'Punjabi Swag',
    foodname: 'North Indian, Mughlai, Chinese, Chicken',
    price: '144',
    image: require('../assets/chicken/img7.webp'),
    offer: '46% OFF today ',
    distance: '39 mins',
    location: 'Bangalore',
    rating: '4.9',
  },
  {
    sno: '68',
    id: '7',
    title: 'Meghana Foods',
    foodname: 'Biryani, Andhra, North Indian, Chicken',
    price: '144',
    image: require('../assets/chicken/img8.webp'),
    offer: '11% OFF today ',
    distance: '22 mins',
    location: 'Bangalore',
    rating: '2.1',
  },
  {
    sno: '69',
    id: '7',
    title: 'Leon Grill',
    foodname: 'Fast Food, Wraps, Chicken',
    price: '135',
    image: require('../assets/chicken/img9.jpg'),
    offer: '26% OFF today ',
    distance: '36 mins',
    location: 'Bangalore',
    rating: '4.3',
  },
  {
    sno: '70',
    id: '7',
    title: 'Biryani Pot',
    foodname: 'North Indian, Chicken',
    price: '124',
    image: require('../assets/chicken/img10.webp'),
    offer: '41% OFF today ',
    distance: '33 mins',
    location: 'Bangalore',
    rating: '2.8',
  },
  {
    sno: '71',
    id: '7',
    title: 'Ice Corner',
    foodname: 'Desserts, Ice Cream',
    price: '118',
    image: require('../assets/ice_cream/img1.webp'),
    offer: '23% OFF today ',
    distance: '26 mins',
    location: 'Bangalore',
    rating: '3.2',
  },
  {
    sno: '72',
    id: '7',
    title: 'GudBud',
    foodname: 'Ice Cream, Beverages',
    price: '133',
    image: require('../assets/ice_cream/img2.webp'),
    offer: '37% OFF today ',
    distance: '26 mins',
    location: 'Bangalore',
    rating: '2.8',
  },
  {
    sno: '73',
    id: '7',
    title: 'Polar Bear',
    foodname: 'Desserts, Ice Cream',
    price: '150',
    image: require('../assets/ice_cream/img3.webp'),
    offer: '32% OFF today ',
    distance: '40 mins',
    location: 'Bangalore',
    rating: '4.2',
  },
  {
    sno: '74',
    id: '7',
    title: 'Natural Ice Cream',
    foodname: 'Ice Cream, Beverages',
    price: '145',
    image: require('../assets/ice_cream/img4.webp'),
    offer: '22% OFF today ',
    distance: '25 mins',
    location: 'Bangalore',
    rating: '4.5',
  },
  {
    sno: '75',
    id: '7',
    title: 'Cream Stone',
    foodname: 'Ice Cream, Desserts',
    price: '144',
    image: require('../assets/ice_cream/img5.webp'),
    offer: '35% OFF today ',
    distance: '39 mins',
    location: 'Bangalore',
    rating: '2.3',
  },
  {
    sno: '76',
    id: '7',
    title: 'Lassi Corner',
    foodname: 'Beverages, Ice Cream',
    price: '103',
    image: require('../assets/ice_cream/img6.jpg'),
    offer: '12% OFF today ',
    distance: '29 mins',
    location: 'Bangalore',
    rating: '2.3',
  },
  {
    sno: '77',
    id: '7',
    title: 'The Bangalore Creamery',
    foodname: 'Desserts, Ice Cream',
    price: '118',
    image: require('../assets/ice_cream/img7.jpeg'),
    offer: '14% OFF today ',
    distance: '29 mins',
    location: 'Bangalore',
    rating: '3.9',
  },
  {
    sno: '78',
    id: '7',
    title: 'Apsara Ice Cream',
    foodname: 'Desserts, Ice Cream',
    price: '150',
    image: require('../assets/ice_cream/img8.webp'),
    offer: '30% OFF today ',
    distance: '23 mins',
    location: 'Bangalore',
    rating: '3.7',
  },
  {
    sno: '79',
    id: '7',
    title: 'Corner Cafe Ice Cream',
    foodname: 'Desserts, Ice Cream',
    price: '141',
    image: require('../assets/ice_cream/img9.webp'),
    offer: '47% OFF today ',
    distance: '32 mins',
    location: 'Bangalore',
    rating: '3.5',
  },
  {
    sno: '80',
    id: '7',
    title: 'Tender Cocount',
    foodname: 'Desserts, Ice Cream',
    price: '127',
    image: require('../assets/ice_cream/img10.webp'),
    offer: '28% OFF today ',
    distance: '40 mins',
    location: 'Bangalore',
    rating: '4.2',
  },
  {
    sno: '81',
    id: '9',
    title: 'Hungry Chang',
    foodname: 'Chinese, Noodles',
    price: '120',
    image: require('../assets/noodles/img1.jpeg'),
    offer: '50% OFF today ',
    distance: '29 mins',
    location: 'Bangalore',
    rating: '3.6',
  },
  {
    sno: '82',
    id: '9',
    title: 'Spicy Platter, Noodles',
    foodname: 'North Indian, Chinese',
    price: '137',
    image: require('../assets/noodles/img2.jpeg'),
    offer: '43% OFF today ',
    distance: '32 mins',
    location: 'Bangalore',
    rating: '4.9',
  },
  {
    sno: '83',
    id: '9',
    title: 'Hao Chi',
    foodname: 'Vietnamese, Chinese, Thai, Noodles',
    price: '135',
    image: require('../assets/noodles/img3.jpeg'),
    offer: '27% OFF today ',
    distance: '32 mins',
    location: 'Bangalore',
    rating: '4.4',
  },
  {
    sno: '84',
    id: '9',
    title: 'Momoz',
    foodname: 'chinese, Momos, Seafood, Noodles',
    price: '100',
    image: require('../assets/noodles/img4.jpeg'),
    offer: '24% OFF today ',
    distance: '22 mins',
    location: 'Bangalore',
    rating: '2.1',
  },
  {
    sno: '85',
    id: '9',
    title: 'Namaste',
    foodname: 'South Indian, Beverages, Noodles',
    price: '119',
    image: require('../assets/noodles/img5.jpeg'),
    offer: '14% OFF today ',
    distance: '32 mins',
    location: 'Bangalore',
    rating: '4.9',
  },
  {
    sno: '86',
    id: '9',
    title: 'Beijing Bites',
    foodname: 'Chinese, Oriental, Beverages, Noodles',
    price: '131',
    image: require('../assets/noodles/img6.jpeg'),
    offer: '23% OFF today ',
    distance: '34 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
  {
    sno: '87',
    id: '9',
    title: 'Kannur Food point',
    foodname: 'Kerala, Chinese, Noodles',
    price: '121',
    image: require('../assets/noodles/img7.jpeg'),
    offer: '17% OFF today ',
    distance: '38 mins',
    location: 'Bangalore',
    rating: '3.4',
  },
  {
    sno: '88',
    id: '9',
    title: 'Say Noodles',
    foodname: 'Chinese, Asian, Noodles',
    price: '150',
    image: require('../assets/noodles/img8.jpeg'),
    offer: '19% OFF today ',
    distance: '18 mins',
    location: 'Bangalore',
    rating: '4.1',
  },
  {
    sno: '89',
    id: '9',
    title: 'Chopstick',
    foodname: 'Chinese, Asian, Noodles',
    price: '100',
    image: require('../assets/noodles/img9.jpeg'),
    offer: '26% OFF today ',
    distance: '39 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
  {
    sno: '90',
    id: '9',
    title: 'Yum In My Tum',
    foodname: 'Chinese, North Indian, Noodles',
    price: '142',
    image: require('../assets/noodles/img10.jpeg'),
    offer: '39% OFF today ',
    distance: '16 mins',
    location: 'Bangalore',
    rating: '3.3',
  },
];
